services:
  khiomis-timemanager-pg:
    container_name: khiomis_timemanager_db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=khiomis_timemanager
